server:
  port: 8082
  
spring:
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  profiles:
      active: dev    
  logging:
    file: skill-matrix.log
    path: ~/